### ISSUE TITLE
TLS issues. Very old curl version.

### ISSUE THREAD

**Issue by ccchem** [yauritux/busybox-curl#1]
Could not call Kubernetes API over HTTPS:
* error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by VengefulAncient** [comment]
Still a thing in 2022.

**Comment by yauritux** [comment]
Updated curl just now to the newest version (7.81.0)
