### ISSUE TITLE
/bin/curl: line 1: syntax error: unterminated quoted string

### ISSUE THREAD

**Issue by VengefulAncient** [yauritux/busybox-curl#2]
The updated image produces this error on any `curl` invocation. My suspicion is that the wrong architecture (ARM64 instead of AMD64) is used, judging by updated `Dockerfile`:
```
ADD curl-aarch64 curl
```

**Comment by yauritux** [comment]
I didn't get that issue, and the image was already uploaded to docker hub. I've also tested it by freshly pulling the image from docker hub and it works as expected. Could you test the original image from the one that I uploaded on docker hub ? Otherwise, if you're looking to build it from the Dockerfile, you can just change the curl-binary to match your machine architecture (i.e. AMD64) and rebuild the image from your local machine.

**Comment by VengefulAncient** [comment]
What architecture is your machine running? The repository currently has the `curl-aarch64` binary, indicating that this is for ARM64 (not what most Docker users will be running). If I copy the `curl` binary from the latest image and test it, it's clearly reported as ARM64:
```
$ file curl 
curl: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
```

**Comment by yauritux** [comment]
@VengefulAncient , i'm using Macbook Pro here. And it works properly both when i'm building the image from Dockerfile and pulling from the Docker hub.

**Comment by VengefulAncient** [comment]
That probably explains it. You are most likely on the new MBP with an M1 chip, which is ARM64, so the image works for you. But most people using your image will be running it on cloud servers and personal machines that use x86-64 (AMD64) CPUs, making your image incompatible with them.

**Comment by yauritux** [comment]
@VengefulAncient , I've updated the curl binary to match x86-64 just now. Thanks for your finding.

**Comment by VengefulAncient** [comment]
Thank you so much for fixing it so quickly! Tested and confirmed working :+1: 
```
# curl --version
curl 7.81.0 (x86_64-pc-linux-musl) libcurl/7.81.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.9.0 nghttp2/1.43.0
```

**Comment by marr** [comment]
Is there a way to support both mac and pc here? I am trying to use the image on a m1 mac and now get errors running curl. I suppose I could just revert the commit that changed architectures locally and build the image but maybe there is a better way?
