### ISSUE TITLE
Wrong curl file permissions

### ISSUE THREAD

**Issue by vpinna80** [yauritux/busybox-curl#5]
curl is non executable by non-root user.
This is an issue when attaching as kubernetes debug container to a pod executing as non-root.

`-rwxr--r--    1 root     root       3455920 Jan 19 14:09 curl`

**Comment by yauritux** [comment]
fixed this already in the latest commit. 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/515690/193590291-f6005b8d-87cc-4677-a9a3-8d8f7272c38d.png">
